- id: '1767203897658'
  alias: Lüfen beim Kochen
  description: ''
  triggers:
  - type: power
    device_id: c7e89541ee45d88503fa7aba23b9ea18
    entity_id: 6e0bc241567b3eb1bc4dbb83a2688495
    domain: sensor
    trigger: device
    above: 2
    below: 2
  conditions: []
  actions:
  - if:
    - type: is_power
      condition: device
      device_id: c7e89541ee45d88503fa7aba23b9ea18
      entity_id: 6e0bc241567b3eb1bc4dbb83a2688495
      domain: sensor
      above: 2
    then:
    - action: scene.create
      metadata: {}
      data:
        scene_id: temp_kueche_rollo
        snapshot_entities:
        - cover.smart_roller_shutter_2309047208402470080148e1e9d80454_shutter
    - device_id: 687c751d9ced7000b1f9389f571eed7d
      domain: cover
      entity_id: f40a0adf7128ac6f21c757c21913e590
      type: open
    else:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.temp_kueche_rollo
  mode: single
- id: '1767265312688'
  alias: Arbeitslicht einschalten
  description: ''
  triggers:
  - type: power
    device_id: 4fc7d6f016cbdf3de126ce3243ab30f9
    entity_id: 863846466e78b217de3e43d19ab7845c
    domain: sensor
    trigger: device
    above: 20
    below: 20
  conditions:
  - condition: sun
    after: sunset
    after_offset: -00:15:00
  actions:
  - if:
    - type: is_power
      condition: device
      device_id: 4fc7d6f016cbdf3de126ce3243ab30f9
      entity_id: 863846466e78b217de3e43d19ab7845c
      domain: sensor
      above: 20
    then:
    - action: scene.create
      metadata: {}
      data:
        scene_id: temp_wohnzimmer_leuchten
        snapshot_entities:
        - light.couch
        - light.esstisch
        - light.stehlampe_nyla
        - light.signe_gradient_floor_1
        - light.tischlampe_nessino
        - light.tischlampe_nyla
        - light.hue_gradient_lightstrip_1
        - light.hue_play_gradient_lightstrip_1
        - light.hue_lightstrip_1
        - light.akari_10a
    - action: scene.turn_on
      metadata: {}
      target:
        entity_id: scene.arbeiten
      data: {}
    else:
    - action: scene.turn_on
      metadata: {}
      target:
        entity_id: scene.temp_wohnzimmer_leuchten
      data: {}
  mode: single
- id: '1767279764764'
  alias: Schalte Wohnzimmer ein
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.bewegungsbereich
    to:
    - 'on'
  conditions:
  - condition: sun
    after: sunset
    after_offset: -00:15:00
  - condition: device
    type: is_off
    device_id: 70d045b5174e4c9dac4ae7a048e6cc7c
    entity_id: 8af552d6f5ba1245f4744fbb21dbe0c6
    domain: light
  - condition: device
    type: is_off
    device_id: 92e356361d5f75ed32d172eb5cd1025c
    entity_id: a56d6181c71f7d4541cd10710e6baa82
    domain: light
  - condition: device
    type: is_off
    device_id: b0afa244d93e39d165200bf7a6329c7a
    entity_id: 90df4da0aff9c56dd733ee1f632f2a6f
    domain: light
  - condition: device
    type: is_off
    device_id: 9848eef968a9db7121634559226bbaca
    entity_id: 72f506dac1644f0894c68782f2c91856
    domain: light
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.couch
  mode: single
- id: '1767299504159'
  alias: TV eingeschalten
  description: ''
  triggers:
  - device_id: 39adf7f3684b4710dd6dbd2c63fb2e55
    domain: media_player
    entity_id: ba85666ed102ae937ce9b7129bd43981
    type: turned_on
    trigger: device
  - trigger: state
    entity_id:
    - media_player.apple_tv_wohnzimm
    from:
    - 'off'
  conditions: []
  actions:
  - action: scene.create
    metadata: {}
    data:
      scene_id: temp_wohnzimmer_leuchten
      snapshot_entities:
      - light.couch
      - light.esstisch
      - light.stehlampe_nyla
      - light.signe_gradient_floor_1
      - light.tischlampe_nessino
      - light.tischlampe_nyla
      - light.hue_gradient_lightstrip_1
      - light.hue_lightstrip_1
      - light.hue_play_gradient_lightstrip_1
      - light.akari_10a
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.tv
    data: {}
  mode: single
- id: '1767559003748'
  alias: Rollos nach oben fahren
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: -00:30:00
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.rollos_auf
    data: {}
  mode: single
- id: '1767559076078'
  alias: Rollos nach unten fahren
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 00:30:00
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.rollos_zu
  mode: single
- id: '1767562259083'
  alias: Zu Hause verlassen
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.marco_biedermann
    zone: zone.home
    event: leave
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.zu_hause_verlassen
  mode: single
- id: '1767648542380'
  alias: Licht für Wohnungstür
  description: ''
  triggers:
  - device_id: af3dcaf0d342bcbef1f9ca0d11fbbd89
    domain: lock
    entity_id: 3363b6611711a3871a740401c4d17a8d
    type: unlocked
    trigger: device
  - type: opened
    device_id: 7116eb1320169fb48bc9a32579968153
    entity_id: 56927c0f0828a75b2c16b2b58b949e51
    domain: binary_sensor
    trigger: device
  - device_id: b4529076d1a14f4312e35ae5ee375214
    domain: button
    entity_id: ac2466a8dc6bdd9f65d363a48b12026e
    type: pressed
    trigger: device
  - type: motion
    device_id: af12b7c38d89d8c555544849a199d543
    entity_id: cbb97f6cdb2a9470a4d22a90d1b5f38c
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: scene.create
    metadata: {}
    data:
      scene_id: temp_flur_leuchten
      snapshot_entities:
      - light.spiegel
      - light.wohnungstur
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.zu_hause_ankommen
    data: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.temp_flur_leuchten
    data: {}
  mode: single
- id: '1767805019548'
  alias: Kaffee zubereiten
  description: ''
  triggers:
  - type: changed_states
    device_id: 5106143a62ee944337e1eeae9f57f1c1
    entity_id: 0db09875e731d8ce0a3e587bfd27b9fb
    domain: switch
    trigger: device
  conditions: []
  actions:
  - if:
    - condition: device
      type: is_on
      device_id: 5106143a62ee944337e1eeae9f57f1c1
      entity_id: 0db09875e731d8ce0a3e587bfd27b9fb
      domain: switch
    then:
    - action: scene.create
      metadata: {}
      data:
        scene_id: temp_kueche_leuchten
        snapshot_entities:
        - light.kuche
        - light.kuchenzeile
        - light.gluhbirne_kuche
    - action: light.turn_on
      metadata: {}
      target:
        entity_id: light.kuchenzeile
      data:
        brightness_pct: 40
    else:
    - delay:
        hours: 0
        minutes: 1
        seconds: 30
        milliseconds: 0
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.temp_kueche_leuchten
  mode: single
- id: '1767883769919'
  alias: Benachrichtigung senden, wenn Waschmaschine fertig
  description: ''
  triggers:
  - type: power
    device_id: 9a516f445178413249d6cc9ddcefbecd
    entity_id: bd7dd8a07739cc948fcded413e7f4c3f
    domain: sensor
    trigger: device
    below: 2
  conditions: []
  actions:
  - action: notify.mobile_app_marcos_iphone
    metadata: {}
    data:
      message: Waschmaschine
      title: Waschmaschine ist fertig!
  mode: single
